language: python
python:
  - "3.8"
services:
  - docker
# command to install dependencies
install:
  $ git pull ObjectID-Backend
  $ git pull Object-ID-Frontend
  $ git submodule update --remote
  $ docker-compose up -d --build
# command to run tests
script:
  - python manage.py test
