version: '3'

services:
  db:
    image: postgres
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn --certfile=/code/nginx/objectid.crt --keyfile=/code/nginx/objectid.key config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - 8000
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.envs/.django
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/certs/
    depends_on:
      - web
  redis:
    image: redis:5.0