# Generated by Django 3.0.5 on 2020-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
    ]
