# Generated by Django 3.0.5 on 2020-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='business/logos/'),
        ),
    ]
