# Generated by Django 3.0.5 on 2020-05-31 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10)),
                ('make', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=32)),
                ('saps_flagged', models.BooleanField(default=False)),
                ('license_plate_duplicate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='vehicle.DamageLocation')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='vehicle.DamageType')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='vehicle.Vehicle')),
            ],
        ),
    ]
