# Generated by Django 3.0.5 on 2020-08-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_markedvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
