# Generated by Django 3.0.5 on 2020-09-15 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20200816_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='vehicle.DamageLocation'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage', to='vehicle.DamageType'),
        ),
        migrations.AlterField(
            model_name='damagelocation',
            name='location',
            field=models.CharField(blank=True, choices=[('FR', 'Front'), ('RR', 'Rear'), ('S', 'Side')], default=None, max_length=128, null=True),
        ),
    ]
