# Generated by Django 3.0.5 on 2020-09-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20200915_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='damage_vehicle/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='damagelocation',
            name='location',
            field=models.CharField(blank=True, choices=[('FRONT', 'Front'), ('REAR', 'Rear'), ('SIDE', 'Side')], default=None, max_length=128, null=True),
        ),
    ]
