# Generated by Django 3.0.5 on 2020-09-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_auto_20200916_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedvehicle',
            name='reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
