# Generated by Django 3.0.5 on 2020-10-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_markedvehicle_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate_duplicate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='saps_flagged',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='DamageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='damage_detection/%Y/%m/%d/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_detections', to='vehicle.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_accuracy', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('model_accuracy', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('color_accuracy', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('license_plate_accuracy', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('damage_accuracy', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accuracy', to='vehicle.Vehicle')),
            ],
        ),
    ]
