#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /code/manage.py collectstatic --noinput
/usr/local/bin/gunicorn --certfile=/code/nginx/objectid.crt --keyfile=/code/nginx/objectid.key config.wsgi:application --bind 0.0.0.0:443 --chdir=/code
