# Generated by Django 3.0.5 on 2020-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclelog',
            name='location',
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='vehiclelog',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9),
        ),
    ]
