# Generated by Django 3.0.5 on 2020-08-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
        ('tracking', '0002_auto_20200731_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelog',
            name='camera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='camera.Camera'),
        ),
    ]
